#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'
require 'set'
require 'pathname'
require 'fileutils'

ROOT = Pathname.new(__dir__).parent.freeze
DEFINITIONS = ROOT.join('sources', 'definitions').freeze
HOST_MAPPING = { 'metal' => 'low', 'virtual' => 'medium' }.freeze
DESTINATION = ROOT.join('workspace', 'ansible', 'variables').freeze
INVENTORY = ROOT.join('environment', 'fleet', 'inventory.yml').freeze

def load
  state = {}

  Dir.glob(File.join(DEFINITIONS, '**', '*.yml')).each do |path|
    relative = Pathname.new(path).relative_path_from(DEFINITIONS)
    parent = state
    locator = []
    segments = relative.to_s.split('/')
    filename = segments.pop
    key = File.basename(filename, '.yml')
    segments.each do |part|
      locator.push(part)
      parent[part] ||= {}
      parent = parent[part]
      unless parent.is_a?(Hash)
        raise "Conflicting node at #{locator.join('/')} is #{parent.class} and not a hash: #{parent}"
      end
    end

    parent[File.basename(key)] = YAML.safe_load(File.read(path), permitted_classes: [], permitted_symbols: [], aliases: false)
  end

  state.freeze
end

def merge_packages(core, overlay)
  translate = overlay.fetch('translate', {})
  extra = overlay.fetch('extra', [])
  skip = overlay.fetch('skip', [])

  out = core.flat_map do |package|
    replacement = translate.fetch(package, package)
    replacement.is_a?(Array) ? replacement : [replacement]
  end

  out.concat(extra)

  rejected = skip.to_set
  out = out.reject { |package| rejected.include?(package) }

  out.uniq
end

def to_variables(definition, state)
  host = definition['id']
  kind = definition['kind']
  orbit = HOST_MAPPING[kind]
  domain = "#{orbit}.orbit.mkanes.me"

  sandbox = Marshal.load(Marshal.dump(state))

  current = sandbox['hosts'][kind][host]
  current['orbit'] = orbit
  current['domain'] = domain
  current['name'] = "#{host}.#{domain}"

  sandbox['host'] = current
  sandbox['secrets'].each do |key, tree|
    sandbox[key] = tree
  end

  sandbox.delete('hosts')
  sandbox.delete('secrets')

  distribution = sandbox['host']['os']['distribution']
  overlay = sandbox['packages'].fetch('overlay', {}).fetch(distribution, {})
  sandbox['packages'].delete('overlay')
  packages = sandbox['packages'].map do |key, list|
    [key, merge_packages(list, overlay.fetch(key, {}))]
  end

  sandbox['packages'] = Hash[packages]

  sandbox
end

def to_inventory(state)
  inventory = {
    'all' => {
      'vars' => {
        'ansible_user' => 'relay'
      },
      'hosts' => {}
    }
  }

  HOST_MAPPING.keys.map do |kind|
    pairs = state['hosts'].fetch(kind, {}).map do |host, definition|
      definition['kind'] = kind
      definition['id'] = host
      variables = to_variables(definition, state)
      host = variables['host']['name']
      [host, variables]
    end

    hosts = Hash[pairs]

    inventory['all']['hosts'] = inventory['all']['hosts'].merge(hosts)

    hosts.each do |host, variables|
      definition = variables['host']
      platform = definition.fetch('platform', {})
      os = definition.fetch('os', {})
      groups = []
      architecture = platform.fetch('architecture', nil)
      vendor = platform.fetch('vendor', nil)
      distribution = os.fetch('distribution', nil)
      distribution_flavor = os.fetch('flavor', nil)
      groups.push(architecture) if architecture
      groups.push("#{architecture}.#{vendor}") if architecture and vendor
      groups.push(distribution) if distribution
      groups.push("#{distribution}.#{distribution_flavor}") if distribution and distribution_flavor

      groups.each do |key|
        inventory[key] ||= {}
        inventory[key]['hosts'] ||= {}
        inventory[key]['hosts'][host] = {}
      end
    end
  end

  inventory
end

STATE = load
# noinspection RubyNilAnalysis
FileUtils.mkdir_p(INVENTORY.parent)
File.write(INVENTORY, YAML.safe_dump(to_inventory(STATE)))
summary = STATE['hosts']
  .map { |kind, hosts| "#{hosts.size} #{kind}" }
  .join(', ')
puts "Written #{summary} hosts to #{INVENTORY}"


