#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'
require 'set'
require 'pathname'
require 'fileutils'

ROOT = Pathname.new(__dir__).parent.freeze
DEFINITIONS = ROOT.join('sources', 'definitions')
# @type [Pathname]
# noinspection RubyNilAnalysis
PACKAGES = DEFINITIONS.join('packages')
# @type [Pathname]
SECRETS = File.join(DEFINITIONS, 'secrets')
# @type [Pathname]
DESTINATION = ROOT.join('workspace', 'ansible', 'variables')
TARGETS = %w[ubuntu fedora].freeze

def load_yaml(path)
  YAML.safe_load(File.read(path), permitted_classes: [], permitted_symbols: [], aliases: false)
rescue Errno::ENOENT
  nil
end

def ensure_list(obj, path)
  return obj if obj.is_a?(Array)
  raise "#{path} must be a YAML list (Array), got #{obj.class}"
end

def ensure_hash(obj, path)
  return {} if obj.nil?
  return obj if obj.is_a?(Hash)
  raise "#{path} must be a YAML mapping (Hash), got #{obj.class}"
end

def apply_overlay(path, base, content)
  translate = content.fetch('translate', {})
  extra = content.fetch('extra', [])
  skip = content.fetch('skip', [])

  ensure_hash(translate, path + '#translate')
  ensure_list(extra, path + '#extra')
  ensure_list(skip, path + '#skip')

  out = base.map { |package| translate.fetch(package, package) }
  out.concat(extra)

  rejected = skip.to_set
  out = out.reject { |package| rejected.include?(package) }

  out.uniq
end

FileUtils.mkdir_p(DESTINATION)

base_files = Dir.glob(File.join(PACKAGES, '*.yml')).sort

if base_files.empty?
  warn "No package definition files found in #{PACKAGES}"
  exit 1
end

base_files.each do |path|
  base = ensure_list(load_yaml(path), path)
  yml_name = File.basename(path)

  TARGETS.each do |os|
    overlay_path = File.join(PACKAGES, 'overlay', os, yml_name)
    overlay = ensure_hash(load_yaml(overlay_path), overlay_path)

    compiled = apply_overlay(overlay_path, base, overlay)
    relative_destination = Pathname.new('targeted').join('distribution', os, yml_name)
    # noinspection RubyNilAnalysis
    destination = DESTINATION.join(relative_destination)

    # noinspection RubyNilAnalysis
    FileUtils.mkdir_p(destination.parent)
    File.write(destination, { 'packages' => compiled }.to_yaml)
    puts "Wrote #{compiled.size} packages to #{relative_destination}"
  end
end

Dir.glob(File.join(SECRETS.to_s, '**', '*.yml')).sort.each do |path|
  relative_path = Pathname.new(path).relative_path_from(SECRETS)
  # noinspection RubyNilAnalysis
  relative_destination = Pathname.new('universal')
    .join('secrets')
    .join(relative_path)
  # noinspection RubyNilAnalysis
  destination = DESTINATION.join(relative_destination)
  # noinspection RubyNilAnalysis
  FileUtils.mkdir_p(destination.parent)
  FileUtils.cp(path, destination)
  puts "Copied secret #{relative_path} to #{relative_destination}"
end
