- name: Machine access configuration
  hosts: all
  become: true
  vars:
    administration_accounts:
      - orangepi
      - root

  tasks:
    - name: Define sudo group
      ansible.builtin.set_fact:
        sudo_group: "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' }}"
    - name: Physical access isolation group
      ansible.builtin.group:
        name: isolated
      # There was a fun reaction from one of the machines not creating personal
      # group by default, injecting gid 1000 instead (which pointed to isolated
      # group)
    - name: Per-account groups
      ansible.builtin.group:
        name: "{{ item.value.id if (item.value.id is defined) else item.key }}"
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "Setting up {{ item.key }} personal user group"
    - name: Set up user accounts
      ansible.builtin.user:
        name: "{{ item.value.id if (item.value.id is defined) else item.key }}"
        password: "{{ item.value.password }}"
        group: "{{ item.value.id if (item.value.id is defined) else item.key }}"
        groups: "{{ ([sudo_group] if item.value.get('sudo', false) else []) + (item.value.groups | default([])) }}"
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "Setting up {{ item.key }} user account"
    - name: Get user info from passwd
      ansible.builtin.getent:
        database: passwd
        key: "{{ item }}"
        fail_key: false # Prevents the task from failing if the user is missing
      loop: "{{ administration_accounts }}"
    - name: Filtering existing administration accounts
      ansible.builtin.set_fact:
        isolated_accounts: "{{ isolated_accounts | default([]) + [item] }}"
      loop: "{{ administration_accounts }}"
      when: ansible_facts.getent_passwd[item] is defined
    - name: Adding other administration accounts to the isolated group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: isolated
        append: true
      loop: "{{ isolated_accounts }}"
      loop_control:
        label: "Adding {{ item }} to the isolated group"

  handlers:
    - name: Reload sshd
      ansible.builtin.service:
        name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
        state: reloaded
