- name: Maintenance access configuration
  hosts: all
  become: true
  vars:
    root: "{{ lookup('ansible.builtin.env', 'PWD') }}/workspace/ansible/variables"

  tasks:
    - name: Load relay user
      ansible.builtin.include_vars:
        file: '{{ root }}/universal/secrets/users/relay.yml'
        name: relay
    - name: Load airlock user
      ansible.builtin.include_vars:
        file: '{{ root }}/universal/secrets/users/airlock.yml'
        name: airlock

    - name: Physical access isolation group
      ansible.builtin.group:
        name: isolated
#    - name: Sudo group
#      ansible.builtin.group:
#        name: sudo
    - name: Physical access account
      ansible.builtin.user:
        name: airlock
        password: "{{ airlock['password'] }}"
        groups:
          - "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' }}"
          - isolated
    - name: Remote access account
      ansible.builtin.user:
        name: relay
        password: "{{ relay['password'] }}"
        groups:
          - "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' }}"

    - name: Remote access SSH keys
      ansible.posix.authorized_key:
        user: relay
        state: present
        key: "{{ relay['keys'] | join('\n') }}"
        exclusive: true

    - name: Ensure sshd_config.d exists
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Forbid physical account SSH access
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/99-maintenance-access-rules.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          DenyGroups isolated
          
          Match User relay
            AuthenticationMethods publickey,password
      notify: Reload sshd

    - name: Validate sshd configuration
      ansible.builtin.command: sshd -t
      changed_when: false

  handlers:
    - name: Reload sshd
      ansible.builtin.service:
        name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
        state: reloaded
