- name: Machine access configuration
  hosts: all
  become: true

  tasks:
    - name: Define sudo group
      ansible.builtin.set_fact:
        sudo_group: "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' }}"
    - name: Physical access isolation group
      ansible.builtin.group:
        name: isolated
    - name: Set up user accounts
      ansible.builtin.user:
        name: "{{ item.value.id if (item.value.id is defined) else item.key }}"
        password: "{{ item.value.password }}"
        groups: "{{ ([sudo_group] if item.value.get('sudo', false) else []) + (item.value.groups | default([])) }}"
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "Setting up {{ item.key }} user account"

    - name: Remote access SSH keys
      ansible.posix.authorized_key:
        user: "{{ item.value.id if (item.value.id is defined) else item.key }}"
        state: present
        key: "{{ item.value.get('keys', []) | join('\n') }}"
        exclusive: true
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "Setting keys for {{ item.value.id if (item.value.id is defined) else item.key }}"

    - name: Ensure sshd_config.d exists
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Forbid physical account SSH access
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/99-maintenance-access-rules.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          DenyGroups isolated
          
          Match User relay
            AuthenticationMethods publickey,password
      notify: Reload sshd

    - name: Validate sshd configuration
      ansible.builtin.command: sshd -t
      changed_when: false

  handlers:
    - name: Reload sshd
      ansible.builtin.service:
        name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
        state: reloaded
