- name: Install basic package set
  hosts: all
  become: true
  vars:
    categories:
      - core
      - monitoring
      - containerization
      - virtualization
      - media
  tasks:
    - name: 'Install packages'
      ansible.builtin.include_tasks: packages/tasks.yml
      loop: "{{ categories }}"
      loop_control:
        loop_var: category
