- name: 'Load {{ category }} packages'
  ansible.builtin.include_vars:
    file: '{{ root }}/{{ category }}.yml'

- name: 'Install {{ category }} packages'
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
